version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: 'tuanthanh'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'project-social-spaces'
    ports:
      - "3001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    environment:
      # Database connection
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: 'tuanthanh'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_NAME: 'project-social-spaces'
      # Node environment
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend-network
    command: npm run start:dev

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: